/*
SMÅSNÖRE Kit
by IOIO72 aka Tamio Patrick Honma (https://honma.de)

- The source code of the OpenSCAD files is licensed under the [MIT license](https://opensource.org/license/mit).
- The models generated by the source code are licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)).
*/

/* [Advanced] */

$fn = 200;


/* [Kit] */

type = "multiboard_snap"; // [multiboard_snap:Multiboard Snap, connector:Connector]


/* [SMÅSNÖRE Outer Thread] */

smasnoere_diamater = 17.5;
smasnoere_wall = 1.2;
smasnoere_height = 23.0;
smasnoere_nose_start_from_top = 13.0;
smasnoere_nose_width = 2.7;
smasnoere_nose_height = 2.7;
smasnoere_nose_depth = 1.7;
smasnoere_nose_rotation = 45;


/* SMÅSNÖRE */

module nose() {
  translate(v = [-smasnoere_nose_height / 2, -smasnoere_diamater / 2, 0]) {
    cube([smasnoere_nose_width, smasnoere_nose_depth, smasnoere_nose_height], center = false);
  }
}

module nose_pair() {
  nose();
  rotate(a = 180, v = [0, 0, 1]) {
    nose();
  } 
}

module outer_thread_hole() {
  cylinder(h = smasnoere_height, d = smasnoere_diamater, center = false);  
}

module outer_thread_base() {
  difference() {
    cylinder(h = smasnoere_height, d = smasnoere_diamater + 2 * smasnoere_wall, center = false);
    outer_thread_hole();
  }
}

module outer_thread() {
  outer_thread_base();
  translate(v =[0, 0, smasnoere_height - smasnoere_nose_start_from_top - smasnoere_nose_height]) {
    rotate(a = smasnoere_nose_rotation, v = [0, 0, 1]) {
      nose_pair();
    }
  }
}


/* Multiboard */

module multiboard_snap_base() {
  import(file = "remix/Blank Snap Standard.stl", center = false, dpi = 96, convexity = 1);
}

module multiboard_snap() {
  difference() {
    multiboard_snap_base();
    outer_thread_hole();
  }
}


/* Main */

if (type == "multiboard_snap") {
  multiboard_snap();
}

if (type == "connector") {
  rotate(a = 180, v = [0, 1, 0]) {
    outer_thread();
  }
}

outer_thread();
